- name: Install nginx
  apt: >
    pkg=nginx
    update_cache=yes
    cache_valid_time=3600
    state=latest
    force=yes
  tags: nginx

- name: Copy config default
  template: >
    src=default.j2
    dest=/etc/nginx/sites-available/default
  notify: restart nginx
  tags:
    - nginx
