---
- name: Create dir unicorn config
  command: mkdir -p /etc/unicorn
  tags:
    - unicorn

- name: Configure unicorn for project
  template: >
    src=unicorn.conf.j2
    dest=/etc/unicorn/{{app_name}}.rb
  tags:
    - unicorn

- name: Create shared folders for project
  command: mkdir -p shared/pids shared/sockets shared/log
  become: yes
  become_user: consul
  args:
    chdir: /home/consul/consul
  tags:
    - unicorn

- name: Copy unicorn.rb in project
  template: >
    src=unicorn.rb.j2
    dest=/home/consul/consul/config/unicorn.rb
  become: yes
  become_user: consul
  tags:
    - unicorn

- name: Create init file for project
  template: >
    src=init_unicorn.j2
    dest=/etc/init.d/unicorn_{{app_name}}
  tags:
    - unicorn

- name: Change permissions for init file
  command: chmod 755 /etc/init.d/unicorn_{{app_name}}
  tags:
    - unicorn

- name: update-rc.d
  command: update-rc.d unicorn_{{app_name}} defaults
  notify: restart unicorn
  tags:
    - unicorn
