---
- name: Set Rails Environment
  template: >
      src=env.sh.j2
      dest=/etc/profile.d/env.sh
  tags: setup

- name: Install extra packages
  apt: "pkg={{item}} state=latest force=yes update_cache=yes"
  with_items:
    - vim
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - nodejs
    - npm
  tags: setup

- name: Create user for Consul
  user:
    name=consul
    group={{ linux_usergroup }}
    password={{ linux_userpassword }}
    comment="Consul user"
    shell=/bin/bash
    state=present
  tags: setup
